# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

.PHONY: aws/cli-version
## Display AWS CLI version
aws/cli-version:
	@echo "--- AWS CLI ---"
	@aws --version
