# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

.PHONY: gomplate/version
## Display Gomplate version
gomplate/version:
	@echo "--- GOMPLATE ---"
	@gomplate --version
