# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

export WORKSPACE:=$(shell pwd)

include $(WORKSPACE)/.devcontainer/lib/make/Makefile
include $(WORKSPACE)/.devcontainer/lib/make/*/Makefile
