# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

.PHONY: terrascan/run
## Run Terrascan
terrascan/run:
	terrascan scan

.PHONY: terrascan/version
## Display Terrascan version
terrascan/version:
	@echo "--- TERRASCAN ---"
	@terrascan version
