# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

.PHONY: tfsec/run
## Run TFSEC
tfsec/run:
	tfsec .

.PHONY: tfsec/version
## Display TFSEC version
tfsec/version:
	@echo "--- TFSEC ---"
	@tfsec --version
