# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

.PHONY: tfswitch/run
## Execute tfswitch
tfswitch/run:
	@tfswitch
	@terraform -version

.PHONY: tfswitch/version
## Display tfswitch version
tfswitch/version:
	@echo "--- TFSWITCH ---"
	@tfswitch --version
