# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

.PHONY: go/install
## Install Golang
go/install:
	sudo apt-get -qq install --yes golang

.PHONY: go/version
## Display Go version
go/version:
	@echo "--- GO ---"
	@go version
